/**
 * Shared enum constants (BUG-023).
 * Single source of truth for all valid enum values used across controllers.
 * Import from here instead of re-declaring inline in each controller.
 */

const VALID_INQUIRY_SOURCES = [
  'WALK_IN',
  'PHONE_CALL',
  'WEBSITE',
  'WHATSAPP',
  'REFERRAL',
  'ADVERTISEMENT',
  'OTHER',
];

const VALID_INQUIRY_STAGES = [
  'NEW',
  'CONTACTED',
  'QUALIFIED',
  'SITE_VISIT_SCHEDULED',
  'NEGOTIATION',
  'BOOKED',
  'NOT_INTERESTED',
];

const VALID_UNIT_STATUSES = ['AVAILABLE', 'RESERVED', 'SOLD'];
const MANUAL_UNIT_STATUSES = ['AVAILABLE', 'SOLD']; // RESERVED is booking-managed

const VALID_SITE_VISIT_STATUSES = ['SCHEDULED', 'COMPLETED', 'CANCELLED', 'RESCHEDULED'];
const MANUAL_SITE_VISIT_STATUSES = ['SCHEDULED', 'RESCHEDULED', 'CANCELLED'];

const VALID_QUOTATION_DECISIONS = ['PENDING', 'NEGOTIATING', 'ACCEPTED', 'REJECTED'];

const VALID_PAYMENT_MODES = ['CASH', 'CHEQUE', 'BANK_TRANSFER', 'UPI', 'CARD', 'OTHER'];

const VALID_DOCUMENT_TYPES = [
  'BOOKING_FORM',
  'SIGNED_AGREEMENT',
  'ID_PROOF',
  'PAYMENT_PROOF',
  'OTHER',
];

const VALID_INTERACTION_TYPES = ['CALL', 'MEETING', 'WHATSAPP', 'EMAIL', 'NOTE'];

// ─── Module 5: Contract, Due Diligence & Financing ───────────────────────────

const VALID_CONTRACT_DOCUMENT_TYPES = [
  'SALE_AGREEMENT',
  'ALLOTMENT_LETTER',
  'NOC',
  'TITLE_DEED',
  'CUSTOMER_ID_PROOF',
  'CUSTOMER_ADDRESS_PROOF',
  'LOAN_SANCTION_LETTER',
  'OTHER',
];

const VALID_SIGNATURE_STATUSES = ['PENDING', 'SIGNED', 'REJECTED'];

const VALID_DUE_DILIGENCE_STATUSES = ['PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED'];

const VALID_FINANCING_TYPES = [
  'SELF_FUNDED',
  'HOME_LOAN',
  'CONSTRUCTION_LINKED_PLAN',
  'OTHER',
];

const VALID_FINANCING_APPROVAL_STATUSES = [
  'NOT_APPLIED',
  'APPLIED',
  'APPROVED',
  'REJECTED',
];

// ─── Module 6: Transaction Execution & Closing ───────────────────────────────

const VALID_TRANSACTION_STATUSES = ['PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'];

const VALID_INVOICE_STATUSES = ['DRAFT', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'OVERDUE'];

const VALID_TRANSACTION_PAYMENT_STATUSES = ['PENDING', 'RECONCILED'];

const VALID_TITLE_TRANSFER_STATUSES = ['NOT_STARTED', 'IN_PROGRESS', 'COMPLETED'];

module.exports = {
  VALID_INQUIRY_SOURCES,
  VALID_INQUIRY_STAGES,
  VALID_UNIT_STATUSES,
  MANUAL_UNIT_STATUSES,
  VALID_SITE_VISIT_STATUSES,
  MANUAL_SITE_VISIT_STATUSES,
  VALID_QUOTATION_DECISIONS,
  VALID_PAYMENT_MODES,
  VALID_DOCUMENT_TYPES,
  VALID_INTERACTION_TYPES,
  VALID_CONTRACT_DOCUMENT_TYPES,
  VALID_SIGNATURE_STATUSES,
  VALID_DUE_DILIGENCE_STATUSES,
  VALID_FINANCING_TYPES,
  VALID_FINANCING_APPROVAL_STATUSES,
  VALID_TRANSACTION_STATUSES,
  VALID_INVOICE_STATUSES,
  VALID_TRANSACTION_PAYMENT_STATUSES,
  VALID_TITLE_TRANSFER_STATUSES,
};
