/**
 * Shared enum constants (BUG-023).
 * Single source of truth for all valid enum values used across controllers.
 * Import from here instead of re-declaring inline in each controller.
 */

const VALID_INQUIRY_SOURCES = [
  'WALK_IN',
  'PHONE_CALL',
  'WEBSITE',
  'WHATSAPP',
  'REFERRAL',
  'ADVERTISEMENT',
  'OTHER',
];

const VALID_INQUIRY_STAGES = [
  'NEW',
  'CONTACTED',
  'QUALIFIED',
  'SITE_VISIT_SCHEDULED',
  'NEGOTIATION',
  'BOOKED',
  'NOT_INTERESTED',
];

const VALID_UNIT_STATUSES = ['AVAILABLE', 'RESERVED', 'SOLD'];
const MANUAL_UNIT_STATUSES = ['AVAILABLE', 'SOLD']; // RESERVED is booking-managed

const VALID_SITE_VISIT_STATUSES = ['SCHEDULED', 'COMPLETED', 'CANCELLED', 'RESCHEDULED'];
const MANUAL_SITE_VISIT_STATUSES = ['SCHEDULED', 'RESCHEDULED', 'CANCELLED'];

const VALID_QUOTATION_DECISIONS = ['PENDING', 'NEGOTIATING', 'ACCEPTED', 'REJECTED'];

const VALID_PAYMENT_MODES = ['CASH', 'CHEQUE', 'BANK_TRANSFER', 'UPI', 'CARD', 'OTHER'];

const VALID_DOCUMENT_TYPES = [
  'BOOKING_FORM',
  'SIGNED_AGREEMENT',
  'ID_PROOF',
  'PAYMENT_PROOF',
  'OTHER',
];

const VALID_INTERACTION_TYPES = ['CALL', 'MEETING', 'WHATSAPP', 'EMAIL', 'NOTE'];

// Cap on how many units can be generated in one bulk-create request.
const MAX_BULK_UNITS = 500;

module.exports = {
  VALID_INQUIRY_SOURCES,
  VALID_INQUIRY_STAGES,
  VALID_UNIT_STATUSES,
  MANUAL_UNIT_STATUSES,
  VALID_SITE_VISIT_STATUSES,
  MANUAL_SITE_VISIT_STATUSES,
  VALID_QUOTATION_DECISIONS,
  VALID_PAYMENT_MODES,
  VALID_DOCUMENT_TYPES,
  VALID_INTERACTION_TYPES,
  MAX_BULK_UNITS,
};
