-- AlterTable
ALTER TABLE "Booking" ALTER COLUMN "finalAmount" SET DATA TYPE INTEGER,
ALTER COLUMN "discountAmount" SET DEFAULT 0,
ALTER COLUMN "discountAmount" SET DATA TYPE INTEGER,
ALTER COLUMN "bookingAmount" SET DATA TYPE INTEGER;

-- AlterTable
ALTER TABLE "BookingPayment" ALTER COLUMN "amount" SET DATA TYPE INTEGER;

-- AlterTable
ALTER TABLE "Negotiation" ALTER COLUMN "offeredPrice" SET DATA TYPE INTEGER,
ALTER COLUMN "discountAmount" SET DEFAULT 0,
ALTER COLUMN "discountAmount" SET DATA TYPE INTEGER;

-- AlterTable
ALTER TABLE "Quotation" ALTER COLUMN "basePrice" SET DATA TYPE INTEGER,
ALTER COLUMN "totalAmount" SET DATA TYPE INTEGER;

-- AlterTable
ALTER TABLE "QuotationCharge" ALTER COLUMN "amount" SET DATA TYPE INTEGER;

-- AlterTable
ALTER TABLE "Unit" ALTER COLUMN "pricePerSqFt" SET DATA TYPE INTEGER,
ALTER COLUMN "basePrice" SET DATA TYPE INTEGER;

